#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

#./Allrun.pre

rm -rf processor* log.decomposePar log.rhoSimpleFoam log.reconstructPar log.renumberMesh postProcessing logs

restore0Dir

runApplication decomposePar 

runParallel $(getApplication)

runApplication reconstructPar

rhoSimpleFoam -postProcess -func wallShearStress

rm -rf processor*

./plotResiduals
./plotFM

#------------------------------------------------------------------------------
