#!/bin/bash

# Code for plotting residuals and forces

#foamLog log.rhoSimpleFoam >/dev/null

gnuplot -persist > /dev/null 2>&1 << EOF

set terminal wxt size 600,800

set multiplot
set size 1,0.5
set origin 0.0,0.5; 
set logscale x
set title "Forces vs. Iteration"
set xlabel "Iteration"
set ylabel "Forces [N]";
plot [100:] '<sed -e "s/[(,)]//g" ./postProcessing/forces/0/force.dat' using 1:2 with lines title 'F_X',\
'<sed -e "s/[(,)]//g" ./postProcessing/forces/0/force.dat' using 1:3 with lines title 'F_Y',\
'<sed -e "s/[(,)]//g" ./postProcessing/forces/0/force.dat' using 1:4 with lines title 'F_Z'


set origin 0.0,0.0; 
set title "Moments vs. Iteration"
set xlabel "Iteration"
set ylabel "Moments [N.m]";
plot [100:] '<sed -e "s/[(,)]//g" ./postProcessing/forces/0/moment.dat' using 1:2 with lines title 'M_X',\
'<sed -e "s/[(,)]//g" ./postProcessing/forces/0/moment.dat' using 1:3 with lines title 'M_Y',\
'<sed -e "s/[(,)]//g" ./postProcessing/forces/0/moment.dat' using 1:4 with lines title 'M_Z'
unset multiplot

EOF


