#!/bin/bash

# Code for plotting residuals

foamLog log.rhoSimpleFoam >/dev/null

gnuplot -persist > /dev/null 2>&1 << EOF
set logscale y
set title "Residual vs. Iteration"
set xlabel "Iteration"
set ylabel "Residual"
plot "logs/Ux_0" with lines title 'Residual U_X',\
"logs/Uy_0" with lines title 'Residual U_Y',\
"logs/Uz_0" with lines title 'Residual U_Z',\
"logs/p_0" with lines title 'Residual p',\
"logs/nuTilda_0" with lines title 'Residual nuTilda'

EOF
